### ISSUE TITLE
Windows 7 32bit Visual Studio 2013 6 projects failed to compile

### ISSUE THREAD

**Issue by meiry** [urho3d/Urho3D#1530]
Hey 
i successfully compiled Build: 73 succeeded, 6 failed, example projects , after cmake generated the Solution files 
but those 6 are failed : 
```
Error	71	error MSB4018: The "CustomBuild" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path 'C:\Users\meirmaya\AppData\Local\Temp\tmp56940b9e8a534791a2609419349e80ad.cmd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	Assimp
Error	72	error MSB4018: The "CustomBuild" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path 'C:\Users\meirmaya\AppData\Local\Temp\tmp95fc13ebb5554c488ca07a7709d57cc3.cmd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	36_Urho2DTileMap
Error	73	error MSB4018: The "CustomBuild" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path 'C:\Users\meirmaya\AppData\Local\Temp\tmpc8d99994dcea47d3b09158a364394dd7.cmd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	40_Localization
Error	74	error MSB4018: The "CustomBuild" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path 'C:\Users\meirmaya\AppData\Local\Temp\tmpf10471c0a313466da088a76b6211b494.cmd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	AssetImporter
Error	75	error MSB4018: The "CustomBuild" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path 'C:\Users\meirmaya\AppData\Local\Temp\tmp45d17b4e6ce3478a841cdd10324a916f.cmd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	18_CharacterDemo
Error	76	error MSB4018: The "CustomBuild" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path 'C:\Users\meirmaya\AppData\Local\Temp\tmpedfe00c8ae8947baad71503520ca5e5b.cmd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	19_VehicleDemo

```

**Comment by weitjong** [comment]
It does not make any sense. The same script is responsible for all the sample targets when the build tree is being generated.

**Comment by cadaver** [comment]
This does not sound like something that the Urho build system could be responsible of. Can be a problem with OS settings, lacking disk space etc. Fresh clone also worth trying.

**Comment by meiry** [comment]
its fresh clone , there is disk space 
what else can i post here to analyze the problem ?

**Comment by cadaver** [comment]
Here may be something similar or related. Try updating to newest CMake and you could also try cleaning your temp directory.

https://cmake.org/Bug/view.php?id=11584

**Comment by meiry** [comment]
Sorry close this issue , must be something wrong with cmake , now it is working fine
