### ISSUE TITLE
Emscripten sample failed to build on windows

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [urho3d/Urho3D#2446]
### environment
Windows 10

### emscripten:
emscripten-1.38.30
sdk-1.38.30-64bit
java-8.152-64bit
node-8.9.1-64bit
clang-e1.38.30-64bit
mingw-7.1.0-64bit
python-2.7.13.1-64bit

### additional info

Project was generated from script\cmake_emscripten.bat
This happens when node.exe was doing something right after whatever asm2wasm.exe was doing completes.

Is this my mistake, Urho or an upstream bug?
Desktop demo compiles without any problem.

```
cd /d E:\sandbox\Urho3D\build_emscripten\Source\Tools\Urho3DPlayer && "C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\Urho3DPlayer.dir\link.txt --verbose=1
c:\LITEFAST\emsdk\emscripten\1.38.30\em++.bat --sysroot=c:/LITEFAST/emsdk/emscripten/1.38.30/system  -std=c++11 -Wno-invalid-offsetof -mno-sse -Wno-warn-absolute-paths -Wno-unknown-warning-option -Qunused-arguments -Oz -DNDEBUG  -s EXTRA_EXPORTED_RUNTIME_METHODS="['Pointer_stringify']" -s FORCE_FILESYSTEM=1  -O3 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 --memory-init-file 0 -rdynamic -s TOTAL_MEMORY=134217728 -s ALLOW_MEMORY_GROWTH=1 --pre-js "C:/LITEFAST/emsdk/emscripten/1.38.30/src/emrun_prejs.js" -s NO_EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s WASM=1 --preload-file "E:/sandbox/Urho3D/build_emscripten/bin/CoreData.pak"@"CoreData.pak" --use-preload-cache --preload-file "E:/sandbox/Urho3D/build_emscripten/bin/Data.pak"@"Data.pak" --use-preload-cache --shell-file "E:/sandbox/Urho3D/build_emscripten/Source/shell.html" @CMakeFiles\Urho3DPlayer.dir\objects1.rsp  -o ..\..\..\bin\Urho3DPlayer.html @CMakeFiles\Urho3DPlayer.dir\linklibs.rsp
emcc:INFO: Enabling --no-heap-copy because -s ALLOW_MEMORY_GROWTH=1 is being used with file_packager.py (pass --no-heap-copy to suppress this notification)
parseTools.js preprocessor error in shell.html:1: "#!/usr/bin/env "!

undefined:81
      throw e;
      ^
Unclear preprocessor command on line 0: #!/usr/bin/env
Traceback (most recent call last):
  File "c:\LITEFAST\emsdk\emscripten\1.38.30\emcc.py", line 3276, in <module>
    sys.exit(run(sys.argv))
  File "c:\LITEFAST\emsdk\emscripten\1.38.30\emcc.py", line 2228, in run
    memfile, optimizer)
  File "c:\LITEFAST\emsdk\emscripten\1.38.30\emcc.py", line 3091, in generate_html
    wasm_binary_target, memfile, optimizer)
  File "c:\LITEFAST\emsdk\emscripten\1.38.30\emcc.py", line 2864, in generate_traditional_runtime_html
    shell = read_and_preprocess(options.shell_path)
  File "c:\LITEFAST\emsdk\emscripten\1.38.30\tools\shared.py", line 3250, in read_and_preprocess
    run_js(path_from_root('tools/preprocessor.js'), NODE_JS, args, True, stdout=open(stdout, 'w'), cwd=path)
  File "c:\LITEFAST\emsdk\emscripten\1.38.30\tools\shared.py", line 1091, in run_js
    return jsrun.run_js(filename, engine, *args, **kw)
  File "c:\LITEFAST\emsdk\emscripten\1.38.30\tools\jsrun.py", line 155, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['c:/LITEFAST/emsdk/node/8.9.1_64bit/bin/node.exe', 'c:\\LITEFAST\\emsdk\\emscripten\\1.38.30\\tools/preprocessor.js', 'C:\\Users\\MAINAC~1\\AppData\\Local\\Temp\\emscripten_temp_7zdjzm\\settings.js', 'shell.html'] to finish with return code 0, but it returned with code 1 instead! Output:
Source\Tools\Urho3DPlayer\CMakeFiles\Urho3DPlayer.dir\build.make:88: recipe for target 'bin/Urho3DPlayer.html' failed
mingw32-make.exe[2]: *** [bin/Urho3DPlayer.html] Error 1
mingw32-make.exe[2]: Leaving directory 'E:/sandbox/Urho3D/build_emscripten'
CMakeFiles\Makefile2:1270: recipe for target 'Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/all' failed
mingw32-make.exe[1]: *** [Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/all] Error 2
mingw32-make.exe[1]: Leaving directory 'E:/sandbox/Urho3D/build_emscripten'
Makefile:150: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

```

**Comment by weitjong** [comment]
Unfortunately we are rather short-handed at the moment. Our web build has not been upgraded to track the latest changes in the Emscripten yet. You may have to lower your EMSDK to version 1.38.4 in order to do the Web build successfully.

**Comment by UNDEFINED-BEHAVIOR** [comment]
Downgrading to 1.38.4 works.
Guess I should have just take a peek at the test build to see the exact setup.
https://travis-ci.org/urho3d/Urho3D/jobs/528031807

Some suggession:
Make cmake printout warning that active emsdk version is higher then test environment.

**Comment by weitjong** [comment]
Thanks for your suggestion. However, in general it is not always the case that newer EMSDK version (than our tested version) would not work with our Web build. I believe a few versions up from 1.38.4 would still work just fine. But since we do not track closely with Emscripten development, I cannot tell precisely which EMSDK version actually breaks our Web build. You are welcome to submit PR to provide this information in our online documentation. Better still, a PR that will bring our Web build to be compatible with the latest EMSDK again.

**Comment by UNDEFINED-BEHAVIOR** [comment]
@weitjong one more thing to report.

URHO3D_LIB_TYPE=Module option apparently fails, even on 1.38.4

**Comment by weitjong** [comment]
The Module lib type is still experimental and it was introduced when asm.js was still the default build option. The default now is WASM. However, the Module lib type does not work with WASM yet. So, if you want to try it, you will have to also turn off the WASM build option (fallback to use asm.js). That's how our Web CI does it by the way.
