### ISSUE TITLE
Random Crashes in Web Sample 07

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2478]
It doesn't happen at any consistent amount of time, but after a few seconds of moving around in the [AngelScript version of Sample 07](https://urho3d.github.io/samples/Urho3DPlayer.html?Scripts/07_Billboards.as) there is an error thrown about a float not being representable as an integer, which causes the sample to stop. Potentially this happens with other samples, I just noticed it on my own build and then confirmed it on the github hosted ones with that particular sample. 
This is on Google Chrome version 76.0.3809.100 (Official Build) (64-bit) on Ubuntu 16.04 LTS
<hide>
LOG:
```
/samples/Urho3D.js:257 loading /home/travis/build/urho3d/Build/bin/Urho3D.js.data from remote
Urho3DPlayer.html?Scripts/07_Billboards.as:
1243 [Wed Aug 14 02:05:40 2019] INFO: Opened log file Urho3D.log
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Added resource package /Data.pak
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Added resource package /CoreData.pak
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Set screen mode 1024x768 windowed monitor 0
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Initialized input
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Initialized user interface
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Initialized renderer
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] WARNING: Could not get application preferences directory
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Set audio mode 44100 Hz stereo interpolated
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:40 2019] INFO: Initialized engine
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:41 2019] INFO: Scripts/07_Billboards.as:30,1 Compiling void CreateScene()
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:41 2019] WARNING: Scripts/07_Billboards.as:124,15 Variable 'lightNode' hides another variable of same name in outer scope
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:41 2019] WARNING: Scripts/07_Billboards.as:125,16 Variable 'light' hides another variable of same name in outer scope
Urho3DPlayer.html?Scripts/07_Billboards.as:1243 [Wed Aug 14 02:05:41 2019] INFO: Compiled script module Scripts/07_Billboards.as
Urho3DPlayer.html?Scripts/07_Billboards.as:1255 exception thrown: RuntimeError: float unrepresentable in integer range,RuntimeError: float unrepresentable in integer range
    at wasm-function[1810]:222
    at wasm-function[15879]:41
    at wasm-function[32744]:1499
    at wasm-function[32746]:288
    at wasm-function[32758]:408
    at wasm-function[32763]:54
    at wasm-function[6597]:174
    at wasm-function[25600]:3
    at wasm-function[20524]:15
    at Object.dynCall_vi (https://urho3d.github.io/samples/Urho3DPlayer.js:1:386443)
printErr @ Urho3DPlayer.html?Scripts/07_Billboards.as:1255
Urho3DPlayer.js:1 Uncaught RuntimeError: float unrepresentable in integer range
    at wasm-function[1810]:222
    at wasm-function[15879]:41
    at wasm-function[32744]:1499
    at wasm-function[32746]:288
    at wasm-function[32758]:408
    at wasm-function[32763]:54
    at wasm-function[6597]:174
    at wasm-function[25600]:3
    at wasm-function[20524]:15
    at Object.dynCall_vi (https://urho3d.github.io/samples/Urho3DPlayer.js:1:386443)
```

**Comment by weitjong** [comment]
This is a known issue and has been discussed before here. It was last discussed in. https://github.com/urho3d/Urho3D/issues/2447

We could either try to figure out how to prevent the exception is thrown or just close our eyes and just change the WASM trapping mode to behave more like asmjs in the past.

**Comment by Modanung** [comment]
@weitjong Can this be closed?

**Comment by weitjong** [comment]
Yes, thanks.

Info for other watchers. Fixed in master branch since switching to LLVM WASM backend which has different default trapping mode than Fastcomp backend.
