### ISSUE TITLE
Win32 , when changing from debug to Release in new project  in VC 2013 still points to Urho3D_d.lib

### ISSUE THREAD

**Issue by meiry** [urho3d/Urho3D#884]
When first building the new project named Test1 in debug first with this CMAKE command :  
```
D:\dev\cpp\3d\Urho3d\Projects\Test1>cmake_vs2013.bat d:\dev\cpp\3d\Urho3d\Projects\Test1\build -DURHO3D_ANGELSCRIPT=0 -DURHO3D_SAMPLES=1 -DURHO3D_STATIC_RUNTIME=1 -DURHO3D_WI
N32_CONSOLE=1 -DCMAKE_BUILD_TYPE=Debug -DURHO3D_OPENGL=1 -DURHO3D_HOME=D:\dev\cpp\3d\Urho3d\git\Urho3D\build
```
After opening it in VC it compiles fine to debug , when changing it to Release it still takes the debug lib
![r1](https://cloud.githubusercontent.com/assets/1107316/9807824/5b454a92-5861-11e5-9de4-52e9a83de690.png)

**Comment by Stinkfist0** [comment]
`-DCMAKE_BUILD_TYPE=Debug` causes this, drop that and you should be fine.

**Comment by weitjong** [comment]
This is a known problem. CMake/VS is a multi-config generator, i.e. CMake generates a single *.sln that have Release/RelWithDebInfo/Debug build configurations in it. After opening the solution in VS, user could switch build configuration at will. The problem is, this "switching" does not cause an internal cmake-rerun to reconfigure the project. So, whatever has been setup initially stays. Having library name with suffix "_d" is one of those things. If the initial setup is for Debug then the suffix is set. So, like what @Stinkfist0 has pointed out, you also need to set the CMAKE_BUILD_TYPE correspondingly to match what you have in VS and rerun the cmake to reconfigure. There are other things that may break in this manner too, if you don't do cmake-rerun (I cannot remember it specifically now but you can search for it in the code comments).

**Comment by meiry** [comment]
Yeah now i noticed that also in the main engine tree switching from debug to release cause linking errors , so i understand that for release i need to generate new CMAKE project .  right ?

this is part of the errors i got from switching form debug to release 
```
22>D:\dev\cpp\3d\Urho3d\git\Urho3D\Source\Urho3D\Urho2D\TmxFile2D.cpp(199): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
22>  Urho2D.cpp
22>  Generating Code...
22>LINK : fatal error LNK1181: cannot open input file 'D:/dev/cpp/3d/Urho3d/git/Urho3D/build/Source/ThirdParty/DetourTileCache/Release/DetourTileCache.lib'
23>------ Build started: Project: 21_AngelScriptIntegration, Configuration: Release Win32 ------
24>------ Build started: Project: 23_Water, Configuration: Release Win32 ------
23>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/21_AngelScriptIntegration/CMakeLists.txt
23>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\21_AngelScriptIntegration\CMakeFiles\generate.stamp is up-to-date.
23>  AngelScriptIntegration.cpp
23>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
25>------ Build started: Project: 24_Urho2DSprite, Configuration: Release Win32 ------
25>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/24_Urho2DSprite/CMakeLists.txt
26>------ Build started: Project: 25_Urho2DParticle, Configuration: Release Win32 ------
25>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\24_Urho2DSprite\CMakeFiles\generate.stamp is up-to-date.
26>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/25_Urho2DParticle/CMakeLists.txt
25>  Urho2DSprite.cpp
26>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\25_Urho2DParticle\CMakeFiles\generate.stamp is up-to-date.
26>  Urho2DParticle.cpp
25>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
26>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
27>------ Build started: Project: 26_ConsoleInput, Configuration: Release Win32 ------
27>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/26_ConsoleInput/CMakeLists.txt
27>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\26_ConsoleInput\CMakeFiles\generate.stamp is up-to-date.
27>  ConsoleInput.cpp
28>------ Build started: Project: 27_Urho2DPhysics, Configuration: Release Win32 ------
28>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/27_Urho2DPhysics/CMakeLists.txt
28>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\27_Urho2DPhysics\CMakeFiles\generate.stamp is up-to-date.
28>  Urho2DPhysics.cpp
27>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
28>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
29>------ Build started: Project: 29_SoundSynthesis, Configuration: Release Win32 ------
30>------ Build started: Project: 30_LightAnimation, Configuration: Release Win32 ------
29>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/29_SoundSynthesis/CMakeLists.txt
30>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/30_LightAnimation/CMakeLists.txt
29>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\29_SoundSynthesis\CMakeFiles\generate.stamp is up-to-date.
30>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\30_LightAnimation\CMakeFiles\generate.stamp is up-to-date.
29>  SoundSynthesis.cpp
30>  LightAnimation.cpp
29>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
30>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
31>------ Build started: Project: 31_MaterialAnimation, Configuration: Release Win32 ------
32>------ Build started: Project: 32_Urho2DConstraints, Configuration: Release Win32 ------
31>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/31_MaterialAnimation/CMakeLists.txt
32>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/32_Urho2DConstraints/CMakeLists.txt
31>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\31_MaterialAnimation\CMakeFiles\generate.stamp is up-to-date.
32>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\32_Urho2DConstraints\CMakeFiles\generate.stamp is up-to-date.
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018: The "CustomBuild" task failed unexpectedly.
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018: System.IO.IOException: The process cannot access the file 'C:\Users\meirmaya\AppData\Local\Temp\tmp942b9933ab044a86b2f019fd69bf76e0.cmd' because it is being used by another process.
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018:    at System.IO.File.InternalDelete(String path, Boolean checkHost)
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018:    at System.IO.File.Delete(String path)
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()
31>  MaterialAnimation.cpp
33>------ Build started: Project: 33_Urho2DSpriterAnimation, Configuration: Release Win32 ------
33>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/33_Urho2DSpriterAnimation/CMakeLists.txt
33>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\33_Urho2DSpriterAnimation\CMakeFiles\generate.stamp is up-to-date.
33>  Urho2DSpriterAnimation.cpp
31>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
33>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
34>------ Build started: Project: 34_DynamicGeometry, Configuration: Release Win32 ------
34>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/34_DynamicGeometry/CMakeLists.txt
35>------ Build started: Project: 35_SignedDistanceFieldText, Configuration: Release Win32 ------
34>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\34_DynamicGeometry\CMakeFiles\generate.stamp is up-to-date.
34>  DynamicGeometry.cpp
35>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/35_SignedDistanceFieldText/CMakeLists.txt
35>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\35_SignedDistanceFieldText\CMakeFiles\generate.stamp is up-to-date.
35>  SignedDistanceFieldText.cpp
34>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
35>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
36>------ Build started: Project: 36_Urho2DTileMap, Configuration: Release Win32 ------
37>------ Build started: Project: 18_CharacterDemo, Configuration: Release Win32 ------
36>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/36_Urho2DTileMap/CMakeLists.txt
36>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\36_Urho2DTileMap\CMakeFiles\generate.stamp is up-to-date.
37>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/18_CharacterDemo/CMakeLists.txt
37>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\18_CharacterDemo\CMakeFiles\generate.stamp is up-to-date.
36>  Urho2DTileMap.cpp
37>  Character.cpp
37>  CharacterDemo.cpp
36>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
38>------ Build started: Project: 38_SceneAndUILoad, Configuration: Release Win32 ------
37>  Touch.cpp
38>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/38_SceneAndUILoad/CMakeLists.txt
38>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\38_SceneAndUILoad\CMakeFiles\generate.stamp is up-to-date.
38>  SceneAndUILoad.cpp
37>  Generating Code...
37>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
38>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
39>------ Build started: Project: 39_CrowdNavigation, Configuration: Release Win32 ------
40>------ Build started: Project: 40_Localization, Configuration: Release Win32 ------
39>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/39_CrowdNavigation/CMakeLists.txt
39>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\39_CrowdNavigation\CMakeFiles\generate.stamp is up-to-date.
39>  CrowdNavigation.cpp
40>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/40_Localization/CMakeLists.txt
40>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\40_Localization\CMakeFiles\generate.stamp is up-to-date.
40>  L10n.cpp
39>D:\dev\cpp\3d\Urho3d\git\Urho3D\Source\Samples\39_CrowdNavigation\CrowdNavigation.cpp(328): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
39>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
41>------ Build started: Project: AssetImporter, Configuration: Release Win32 ------
40>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
41>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Tools/AssetImporter/CMakeLists.txt
41>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Tools\AssetImporter\CMakeFiles\generate.stamp is up-to-date.
41>  AssetImporter.cpp
42>------ Build started: Project: 09_MultipleViewports, Configuration: Release Win32 ------
42>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/09_MultipleViewports/CMakeLists.txt
42>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\09_MultipleViewports\CMakeFiles\generate.stamp is up-to-date.
42>  MultipleViewports.cpp
42>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
43>------ Build started: Project: 01_HelloWorld, Configuration: Release Win32 ------
43>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/01_HelloWorld/CMakeLists.txt
43>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\01_HelloWorld\CMakeFiles\generate.stamp is up-to-date.
43>  HelloWorld.cpp
43>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
41>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
44>------ Build started: Project: 02_HelloGUI, Configuration: Release Win32 ------
45>------ Build started: Project: 37_UIDrag, Configuration: Release Win32 ------
45>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/37_UIDrag/CMakeLists.txt
45>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\37_UIDrag\CMakeFiles\generate.stamp is up-to-date.
45>  UIDrag.cpp
46>------ Build started: Project: 03_Sprites, Configuration: Release Win32 ------
46>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/03_Sprites/CMakeLists.txt
46>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\03_Sprites\CMakeFiles\generate.stamp is up-to-date.
46>  Sprites.cpp
45>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
47>------ Build started: Project: 04_StaticScene, Configuration: Release Win32 ------
47>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/04_StaticScene/CMakeLists.txt
47>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\04_StaticScene\CMakeFiles\generate.stamp is up-to-date.
47>  StaticScene.cpp
46>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
48>------ Build started: Project: 05_AnimatingScene, Configuration: Release Win32 ------
48>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/05_AnimatingScene/CMakeLists.txt
48>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\05_AnimatingScene\CMakeFiles\generate.stamp is up-to-date.
47>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
48>  AnimatingScene.cpp
49>------ Build started: Project: 06_SkeletalAnimation, Configuration: Release Win32 ------
49>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/06_SkeletalAnimation/CMakeLists.txt
49>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\06_SkeletalAnimation\CMakeFiles\generate.stamp is up-to-date.
49>  Mover.cpp
48>  Rotator.cpp
49>  SkeletalAnimation.cpp
48>  Generating Code...
48>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
50>------ Build started: Project: 07_Billboards, Configuration: Release Win32 ------
49>  Generating Code...
50>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/07_Billboards/CMakeLists.txt
50>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\07_Billboards\CMakeFiles\generate.stamp is up-to-date.
49>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
50>  Billboards.cpp
51>------ Build started: Project: 08_Decals, Configuration: Release Win32 ------
50>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
52>------ Build started: Project: 10_RenderToTexture, Configuration: Release Win32 ------
52>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/10_RenderToTexture/CMakeLists.txt
52>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\10_RenderToTexture\CMakeFiles\generate.stamp is up-to-date.
52>  RenderToTexture.cpp
53>------ Build started: Project: 11_Physics, Configuration: Release Win32 ------
52>  Rotator.cpp
52>  Generating Code...
52>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
54>------ Build started: Project: OgreImporter, Configuration: Release Win32 ------
54>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Tools/OgreImporter/CMakeLists.txt
55>------ Build started: Project: PackageTool, Configuration: Release Win32 ------
54>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Tools\OgreImporter\CMakeFiles\generate.stamp is up-to-date.
54>  OgreImporter.cpp
55>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Tools/PackageTool/CMakeLists.txt
55>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Tools\PackageTool\CMakeFiles\generate.stamp is up-to-date.
55>  PackageTool.cpp
55>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
56>------ Build started: Project: 12_PhysicsStressTest, Configuration: Release Win32 ------
56>  Building Custom Rule D:/dev/cpp/3d/Urho3d/git/Urho3D/Source/Samples/12_PhysicsStressTest/CMakeLists.txt
56>  CMake does not need to re-run because D:\dev\cpp\3d\Urho3d\git\Urho3D\build\Source\Samples\12_PhysicsStressTest\CMakeFiles\generate.stamp is up-to-date.
56>  PhysicsStressTest.cpp
56>LINK : fatal error LNK1181: cannot open input file '..\..\..\lib\Urho3D.lib'
```

**Comment by weitjong** [comment]
No need to generate a new build tree. Just reconfigure your existing build tree by rerunning cmake with the changed CMAKE_BUILD_TYPE build option.

**Comment by meiry** [comment]
Ok  fair enough , needs to be somehow documented or something ...
